### ISSUE TITLE
"Order Now" Needs to be Redesigned

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#1]
The layout is messy. One needs to fix this

**Comment by beingsie** [comment]
Hi, could I be assigned this?

**Comment by c4coderandcreator** [comment]
Sure @beingsie  !! You can work on this !!

**Comment by beingsie** [comment]
Hi @c4coderandcreator, I came back to view the UI changes you merged yesterday that I had worked on but it seems that you have merged a PR (unknown) that has completely broken the UI changes I worked on.

Just thought I would bring this up to see if you were aware of this?

## Current UI screenshot preview:
<img width="1435" alt="image" src="https://github.com/c4coderandcreator/Flavour-Fusion/assets/140430987/91639fb8-13d4-4b5b-ae39-afa3dcb750f5">

## My changes before this new issue:
![image_2023-10-16_001137609](https://github.com/c4coderandcreator/Flavour-Fusion/assets/140430987/f5f4fbff-615f-4f2e-93ca-47320f319bf1)

**Comment by c4coderandcreator** [comment]
breaking of page is fixed, though we are redesigning that part, I appreciate you pointed out that part !! After certain modification new issues will be added, keep a track in issue section !!
