### ISSUE TITLE
Improve : Order now button on Homepage

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#101]
**Redesign Order Now Button on Homepage**
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/70572678/38852a8a-3be6-4590-920d-21b7dc33db04)

**Improve the colour and hover effect**
make it attractive , keeping website theme in  mind !!

**Comment by AdarshKannarath** [comment]
Please Assign it to me

**Comment by c4coderandcreator** [comment]
Hey @AdarshKannarath  Assigned to you !!

Make sure to follow the contributing guidelines and create PR with UI-Improvement branch not the main branch !!

Don't Forget to give a follow to my Github for more upcoming open source projects and Leave a Star to the Repo For Us !!

**Comment by Fahass** [comment]
I would like to work on this issue.

**Comment by AdarshKannarath** [comment]
Sure @c4coderandcreator
I'll follow the guidlines

**Comment by AdarshKannarath** [comment]
Hello, @c4coderandcreator.
I have a couple of ideas.
1) After hovering the button would fill with a green color from left to right transition.
2) Blob effect after hovering.

**Comment by c4coderandcreator** [comment]
@AdarshKannarath  A demo of implementation will work fine for me !!

**Comment by AdarshKannarath** [comment]
https://github.com/c4coderandcreator/Flavour-Fusion/assets/100022179/9af6322f-9fe3-4d16-a344-31789f52a2ee

**Comment by AdarshKannarath** [comment]
https://github.com/c4coderandcreator/Flavour-Fusion/assets/100022179/10084a0a-432f-456d-9b57-be65fa6e8742


https://github.com/c4coderandcreator/Flavour-Fusion/assets/100022179/3de6a8db-142a-4f83-8f21-63968697cfb5

**Comment by c4coderandcreator** [comment]
Both are good please try these two in dark mode also !!

**Comment by AdarshKannarath** [comment]
Sure

**Comment by AdarshKannarath** [comment]
https://github.com/c4coderandcreator/Flavour-Fusion/assets/100022179/7e9c039e-57ec-4095-aa5c-dc7b7ce01402

I think this minimalistic approach would suit the website.
What do think?
Please give me your opinion!!

**Comment by c4coderandcreator** [comment]
I approve it !! its better than the previous one !! Good work
