### ISSUE TITLE
"Need Strong Hover Effect In Nav Bar Items"

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#103]
**Need Strong Hover Effect In Nav Bar Items**
Also match it with websites theme !!

**Comment by Tusharrgrg** [comment]
hey @c4coderandcreator  i want to work on this.

**Comment by c4coderandcreator** [comment]
Hey @Tusharrgrg it is already done !! please check the other open issues
