### ISSUE TITLE
In Dark mode the text is not visible in order now section

### ISSUE THREAD

**Issue by love-sonkar** [c4coderandcreator/Flavour-Fusion#104]
**Describe the bug**
The text color is not visible in dark mode 

**To Reproduce**
1. Go to order now section
2. Click on dark mode
3. see bug the text is not visible

**Expected behavior**
Text text color should be black

**Screenshots**
![FlavorFusion - Google Chrome 18-10-2023 14_48_46](https://github.com/c4coderandcreator/Flavour-Fusion/assets/82786865/d4e27753-0f59-400c-8ed1-68e1dbf58e79)

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Browser [chrome]
 - Version [latest]

**Additional context**
Assign to me to fix this bug

**Comment by c4coderandcreator** [comment]
@love-sonkar Assigned to you !!

**Comment by c4coderandcreator** [comment]
Hey @love-sonkar Please go with UI-Improvement

**Comment by love-sonkar** [comment]
okay thanks

**Comment by c4coderandcreator** [comment]
I see your hard work @love-sonkar  !! Keep doing 🫂 You will reach your goal soon !! Best Wishes for you !! Also if you haven't gave a follow to my Github , punch that follow button for me and Stay Tuned for more upcoming Open Source Projects .

**Comment by Mahapasad** [comment]
@c4coderandcreator  can I work on this issue?

**Comment by love-sonkar** [comment]
@Mahapasad it's already done bro

**Comment by c4coderandcreator** [comment]
> @c4coderandcreator can I work on this issue?

This issue is closed, check the open ones
