### ISSUE TITLE
bug: the vertical scroll is enabled when sign in page is showed

### ISSUE THREAD

**Issue by nujovich** [c4coderandcreator/Flavour-Fusion#114]
**Describe the bug**
When the user goes to Sign in page, the vertical scroll is enabled, which shloud not happen

![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/48018975/9455f305-52fa-4426-b284-38daabbebc56)

**To Reproduce**
1. Go to '/#sign-in' page
2. Observe the right side of the application
3. The user is able to scroll down
4. The scroll up button shows up

**Expected behavior**
When the user goes to the Sign in page, the vertical scroll is disabled

**Screenshots**

Sign in page

![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/48018975/9455f305-52fa-4426-b284-38daabbebc56)

When closing sign in page

![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/48018975/ff3cf993-775e-4af3-b968-33ef3759a4c3)

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise
 - Browser Chrome
 - Version 118.0.5993.71

**Comment by nujovich** [comment]
Hi @c4coderandcreator ! I've already worked on a fix for this one. Could you please assign it to me ?

**Comment by c4coderandcreator** [comment]
Ya @nujovich  Sure !! You can create PR with main Branch !!

**Comment by c4coderandcreator** [comment]
Hey @nujovich  Thank you so much for your valuable contribution !! It was really helpful !! Leave a follow to my profile for more upcoming projects 🫂
