### ISSUE TITLE
Issue in the dish items in the Menu Section

### ISSUE THREAD

**Issue by Varad0014** [c4coderandcreator/Flavour-Fusion#117]
**Describe the bug**
There are two issues with the dish items:
1. There seems to be a minor spacing issue beneath each dish item, causing the hover property to activate even when the cursor is not directly over the dish item itself.
2. The transition of dish item back to its original state after unhovering is not smooth.

**To Reproduce**
1. Go to Menu section
3. Hover on the the dish items
4. Also hover on the space beneath the dish item
5. See issue

**Expected behavior**
1. The hover property on the dish should not be triggered when we hover below it.
2. The transition after unhovering should be smooth
**Screenshots**
![hover-issue](https://github.com/c4coderandcreator/Flavour-Fusion/assets/77493105/265d2b49-9b5d-4d0a-99c9-82992326a5dd)

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]
 - Version [latest]

**Additional context**
I can fix this issue.

**Comment by c4coderandcreator** [comment]
Thank you @Varad0014
