### ISSUE TITLE
Change the twitter icon to X icon

### ISSUE THREAD

**Issue by Kaniz-Fatma** [c4coderandcreator/Flavour-Fusion#12]
It is better to change the twitter icon to its new X icon. Assign this issue to me as I would like to contribute in this project.
![Screenshot_2023-10-16-13-24-40-46_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/c4coderandcreator/Flavour-Fusion/assets/146003237/29a3514f-2a31-492b-8ec2-83b86b5e4d8d)

**Comment by c4coderandcreator** [comment]
Hi @Kaniz-Fatma  thanks for pointing it out !! But we are not active on socials as of now and it's ok to have that logo here !! Please review the project thoroughly and try to create some value contribution !! Looking forward to your new issue
