### ISSUE TITLE
Fix: Animation issue in sign-in page

### ISSUE THREAD

**Issue by Varad0014** [c4coderandcreator/Flavour-Fusion#126]
**Describe the bug**
There are two minor issues I noticed:
1. When we close the sign-in section, the section abrupty disappears at the end of the animation at the left end.
2. When we click on the sign-in button during the animation of sign-in section, the animation first moves to its' end state and then starts the next animation. This means that if the animation is opening the sign-in section(moving right) and we click on the sign-in button during this, the section starts the closing animation from the other end of the screen. I feel that the closing animation should start from the position where the the section is present when the button was clicked.

**To Reproduce**
1. Click on sign-in button in navbar.
2. Close the sign-in section and see the first problem.
3. Click on sign-in button in when the sign-in section is moving and see the discontinuity.

**Screenshots**
Problem 1.

https://github.com/c4coderandcreator/Flavour-Fusion/assets/77493105/9116890b-dbda-4101-814d-257f22b7909f

Problem 2.

https://github.com/c4coderandcreator/Flavour-Fusion/assets/77493105/30ebc624-7fb5-4195-94f1-3465386c432a

**Expected behavior**
The sign-in section should exhibit the same behavior as demonstrated in the following video

https://github.com/c4coderandcreator/Flavour-Fusion/assets/77493105/c1be8643-82e2-42bb-8872-6f7a4793154b

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]
 - Version [latest]

**Additional context**
I can fix these issues.

**Comment by c4coderandcreator** [comment]
Thank you @Varad0014
