### ISSUE TITLE
FEATURE: LOGO FOR THE WEBSITE

### ISSUE THREAD

**Issue by Rishav9911** [c4coderandcreator/Flavour-Fusion#127]
A logo on the left top of a website is a must for any website nowadays.

 So I can create a logo and add it to the top left of all the pages of the website.
kindlly assign me this issue under hacktoberfest and I can make various logo designs using canva and after the approval I can add it in the website on all pages.

**Comment by c4coderandcreator** [comment]
Hey @Rishav9911  This time we have decided to go without a logo on Navbar !! but if you have a better design !! Please work and share the ss at the time of creating PR

**Comment by Rishav9911** [comment]
Hey there @c4coderandcreator , I created some basic logos according to the styling for the website. Does any of it look acceptable or you could tell me some basic idea of how you would like the logo to be so I could modify it and implement the changes.

![flavour-fusion](https://github.com/c4coderandcreator/Flavour-Fusion/assets/133174630/3ae6aa76-7d75-45cd-8f82-2444b39bb6af)

![FLAVOUR FUSION](https://github.com/c4coderandcreator/Flavour-Fusion/assets/133174630/97c3f757-8577-43e8-98ae-e1175aa21dd5)

![flavour fusion (4)](https://github.com/c4coderandcreator/Flavour-Fusion/assets/133174630/d60633d0-892b-463b-a860-78d04285d0ff)

![flavour fusion (3)](https://github.com/c4coderandcreator/Flavour-Fusion/assets/133174630/594d3d53-c4cb-412d-b39f-914c9fc1fc63)

![flavour fusion (2)](https://github.com/c4coderandcreator/Flavour-Fusion/assets/133174630/2802b30c-1e08-4437-860c-b634c619d742)

![FLAVOUR FUSION (1)](https://github.com/c4coderandcreator/Flavour-Fusion/assets/133174630/157628e9-d325-4239-a8a0-b288957fc089)

**Comment by c4coderandcreator** [comment]
last and 2nd last looks good !! just try playing with colors so that it matches with the website !! keep these logo in a folder while pushing the file

**Comment by c4coderandcreator** [comment]
I appreciate your effort @Rishav9911

**Comment by Rishav9911** [comment]
I am really gald to contribute @c4coderandcreator . I tried some designs , does any of it looks acceptable or do i try some different logos or colour combinations ? kindly review.

![Screenshot (24)](https://github.com/c4coderandcreator/Flavour-Fusion/assets/133174630/10ebe994-a23e-4e49-bb2b-3fa68396ff35)

![Screenshot (23)](https://github.com/c4coderandcreator/Flavour-Fusion/assets/133174630/5d120579-9b3a-4534-a65b-b3e8c0b2914f)

![Screenshot (22)](https://github.com/c4coderandcreator/Flavour-Fusion/assets/133174630/a510e944-3e20-4573-8eef-1b8b7f0163a9)

**Comment by c4coderandcreator** [comment]
2nd last is good try changing that image from square to circle shape !! you can do it via code or you can edit the original image !!

**Comment by Rishav9911** [comment]
I have tried to implement the suggested changes. kindly review it @c4coderandcreator . If you are satisfied kindly allow me to open the PR. 

![Screenshot 2023-10-20 155159](https://github.com/c4coderandcreator/Flavour-Fusion/assets/133174630/4fd75040-9c8c-487d-af9b-7ebb359dbccf)

**Comment by c4coderandcreator** [comment]
match the Flavour Fusion text below the logo with font family we have used on website !!

**Comment by Rishav9911** [comment]
I have submitted the PR as per suggestions kindly review it @c4coderandcreator
