### ISSUE TITLE
fix: home interactive image does not match the background

### ISSUE THREAD

**Issue by NicoleVictory** [c4coderandcreator/Flavour-Fusion#130]
**Describe the bug**
The home background color is #FEFBFB and image background is #FFFFFF, which make the interaction look very unnatural. The contrast is even worse when in dark mode.
**To Reproduce**
1. Go to 'Home'
3. Scroll down to 'Plant Based Meat Salad'

**Expected behavior**
For a clean and immersive look it is expected that the image background had the same color as the page background. Since in this way it feels like you are interacting with the atual "plate" in the page instead of interactin with a white card that "contains" the plate.

**Screenshots**
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/99563517/33308bf3-9871-44a0-b0d2-e6c60c0bb33f)
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/99563517/013c8625-994b-46f1-852f-8b72491862ff)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome

**Additional context**
I'll be happy to work on this issue if  the creators agree with the point of view of the problem. I can easily make the plate image the same color (in both modes) while keeping the shadows and interactiveness

**Comment by c4coderandcreator** [comment]
Thank you for pointing this out !! You can give it a go !! Also make sure you follow the contributing guidelines !! while making PR create it with UI-Improvement branch not the main branch !!

**Comment by c4coderandcreator** [comment]
Hey @NicoleVictory  any update ?
