### ISSUE TITLE
Order Now : Cafe Search

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#132]
### Discussed in https://github.com/c4coderandcreator/Flavour-Fusion/discussions/125

<div type='discussions-op-text'>

<sup>Originally posted by **c4coderandcreator** October 19, 2023</sup>
Hey @VIDYA1980  can we separate by date result on left and By cafe result on right also user should click the cafe to see if they have ordered from there or not !! Feel free to share your ideas over this !! Waiting for your response !!</div>

**Comment by VIDYA1980** [comment]
i would like to work on this

**Comment by c4coderandcreator** [comment]
Assigned to you !!
