### ISSUE TITLE
add shadow in navbar

### ISSUE THREAD

**Issue by Iamdivyak** [c4coderandcreator/Flavour-Fusion#134]
The problem is when we scroll down the navbar is kind of mix with content. adding a shadow will separate the Navbar from the content on the page.

- add the shadow in the navbar.
it will look like this
<img width="953" alt="image" src="https://github.com/c4coderandcreator/Flavour-Fusion/assets/102896170/664c3b5b-b653-41ca-aec2-c992ae01bd8b">

- I would like to work on this. kindly assign with hacktoberfest tag

**Comment by Iamdivyak** [comment]
in dark mode
<img width="939" alt="image" src="https://github.com/c4coderandcreator/Flavour-Fusion/assets/102896170/3347d139-ff50-4592-8adc-c1b4d46574b3">

**Comment by c4coderandcreator** [comment]
ok create a PR with UI Improvement branch !!

**Comment by Iamdivyak** [comment]
done @c4coderandcreator

**Comment by c4coderandcreator** [comment]
Merged @Iamdivyak  !! Thank you for contributing !!
