### ISSUE TITLE
In Footer section social links should have hovering effect.

### ISSUE THREAD

**Issue by gauravsingh1281** [c4coderandcreator/Flavour-Fusion#136]
<img width="1053" alt="Screenshot 2023-10-20 001357" src="https://github.com/c4coderandcreator/Flavour-Fusion/assets/85905403/0be7bff9-1c35-4b54-b73b-d6042368c9b8">

**Comment by gauravsingh1281** [comment]
https://github.com/c4coderandcreator/Flavour-Fusion/assets/85905403/7bb65618-cf0e-4553-b8a8-3a183cdf5552

### Hovering effect like this ⬆️⬆️

**Comment by DeepRahangdale** [comment]
would love to work on this!!
assign me

**Comment by gauravsingh1281** [comment]
@c4coderandcreator Please assign this issue to me under hacktoberfest label.

**Comment by c4coderandcreator** [comment]
> would love to work on this!! assign me

hey @DeepRahangdale  look for any other issue or review the website !! Try to open a new issue , if you find any !!

**Comment by c4coderandcreator** [comment]
Hey @DeepRahangdale @gauravsingh1281  Any Update ?

**Comment by DeepRahangdale** [comment]
@c4coderandcreator i am not assigned to this issue yet!!
