### ISSUE TITLE
Minor UI Improvements

### ISSUE THREAD

**Issue by westerandr** [c4coderandcreator/Flavour-Fusion#14]
* I feel the Sign In button in the hover state should have a border
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/20700150/8d7b9092-885b-4463-97e8-3c9734c2518b)

* The order card images are uneven
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/20700150/5f535a7a-efa9-48d5-bfed-7fcc102bc810)

Kindly assign me this issue as a hacktoberfest label please.

**Comment by c4coderandcreator** [comment]
Hi @westerandr !! The Time user had the cursor on it, the effect will take all the attention but if you want to give it a try, go ahead !!
