### ISSUE TITLE
Fix: Responsiveness of buttons in Order Cards

### ISSUE THREAD

**Issue by Varad0014** [c4coderandcreator/Flavour-Fusion#141]
**Describe the bug**
The buttons in the order cards are not responsive. 

**To Reproduce**
1. Click on Orders in navbar
2. Reduce the screen size and see the responsiveness of buttons in each card.

**Expected behavior**
The buttons should be responsive as we reduce the screen size.

**Screenshots**
![issue](https://github.com/c4coderandcreator/Flavour-Fusion/assets/77493105/318ae0eb-b918-4b51-8e49-7fb1f9782d64)

**Additional context**
I can fix this. It would be great if you assign this to me.

**Comment by Varad0014** [comment]
I will also add the margin at the bottom of text to add space between the text and the button.

**Comment by Varad0014** [comment]
The buttons also exhibit color issues upon the initial opening of the website.
<img width="353" alt="button-issue" src="https://github.com/c4coderandcreator/Flavour-Fusion/assets/77493105/27559bca-f1d3-4aff-bcbc-b074f6f12b8d">
<img width="404" alt="button-hover-issue" src="https://github.com/c4coderandcreator/Flavour-Fusion/assets/77493105/a128411b-a13d-439a-8b9c-801cb776cdbc">

**Comment by c4coderandcreator** [comment]
Thank you @Varad0014
