### ISSUE TITLE
Remove the redundant Home link in the navbar

### ISSUE THREAD

**Issue by aneenajohn** [c4coderandcreator/Flavour-Fusion#145]
**Description:**
- Navbar has the home tab as well the FlavorFusion logo, I think only the Logo is required, we can remove Home tab
- Currently both home and logo takes us to the same section

**To Reproduce**
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/75213145/f3b1d8e0-4a95-4f55-9070-0642f69bc7a9)

**Expected behavior**
- Navbar will have only the below tabs.
    - [FlavorFusion](https://c4coderandcreator.github.io/Flavour-Fusion/#)
    - [Menu](https://c4coderandcreator.github.io/Flavour-Fusion/#)
    - [About](https://c4coderandcreator.github.io/Flavour-Fusion/#allaboutus)
    - [Orders](https://c4coderandcreator.github.io/Flavour-Fusion/#order-landing)
    - [Sign In](https://c4coderandcreator.github.io/Flavour-Fusion/#sign-in)
    - Theme switch button

**Comment by aneenajohn** [comment]
@c4coderandcreator, If you find this a valid issue, Please assign this to me.

**Comment by c4coderandcreator** [comment]
Thanks @aneenajohn for your suggestion but the website is used by all sort of humans ( including visually impaired  ) , this button will help to redirect to home , if we remove this its ok for normal people but visually impaired will have issue navigating to home !!
