### ISSUE TITLE
Enhance the UI when the mobile navbar opens up

### ISSUE THREAD

**Issue by aneenajohn** [c4coderandcreator/Flavour-Fusion#146]
**Describe the bug**
On smaller screens when the hamburger menu opens up, currently it fills in half of the screen, and the background scrolls up while it is open

**To Reproduce**
1. Go to [Flavor Fusion site](https://c4coderandcreator.github.io/Flavour-Fusion/#order-landing)
2. Shrink the screen until the mobile hamburger is visible.
3. Click on hamburger icon

**Expected behavior**
1. Once the mobile menu opens up it should up the entire space below header
2. Background Scroll should be disabled if this menu is open

**Screenshots**
(![Proof](https://github.com/c4coderandcreator/Flavour-Fusion/assets/75213145/df01d3db-7ba3-4de7-b5d5-5d036987d6b7))

**Comment by aneenajohn** [comment]
@c4coderandcreator, If you find this a valid issue, Please assign this to me.

**Comment by c4coderandcreator** [comment]
Ya you can fix this !! @aneenajohn  !! Please follow the guideline for contributing and create PR with UI-Improvement branch !!

**Comment by aneenajohn** [comment]
> Ya you can fix this !! @aneenajohn !! Please follow the guideline for contributing and create PR with UI-Improvement branch !!

Sure!
