### ISSUE TITLE
Fix : forward and back button on browsers 

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#148]
Fix : forward and back button
While pressing back button and forward button , website does not redirect to that location.

1. Go to 'homepage'
2. Click on 'every section'
3. Try clicking  'forward and back button on browser'

**Comment by Neel-07** [comment]
hello @c4coderandcreator can you assign this to me

**Comment by Ishsinghal** [comment]
hey can you assign this to me

**Comment by kashika13** [comment]
@c4coderandcreator can you assign this issue to me

**Comment by c4coderandcreator** [comment]
@Neel-07  Hey !! Work on it and follow the contributing guidelines !!

**Comment by c4coderandcreator** [comment]
Hey @Ishsinghal  and @kashika13  thank you for will to contribute , I am opening 2 more bugs kindly check if you can resolve it !!
