### ISSUE TITLE
Redesign "About us" section

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#15]
About us section looks lot basic, it needs to be redesigned !!

**Comment by kirinryu-dev** [comment]
Hi! can i ask about this issue, i understand more i would like to be assigned this issue!

**Comment by c4coderandcreator** [comment]
Hi @kirinryu-dev just give it better and appealing look  !! Please follow the guidelines of contribution !!

**Comment by c4coderandcreator** [comment]
There are lot more PR's approved to the repo, please pull the repo first to your local machine before you start working on this , (To avoid conflicts ) !!

**Comment by kirinryu-dev** [comment]
Hi i made it look better a bit cool but need help with JS and responsiveness I'm a little unwell I can't work for long periods....how should i procede?

**Comment by c4coderandcreator** [comment]
Please take your time , try to come up with the solution !! There is no rush !!

**Comment by c4coderandcreator** [comment]
This is completed !!
