### ISSUE TITLE
On reload : Menu section and About section redirects to Home 

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#151]
On reload : Menu section and About section redirects to Home 

**To Reproduce**
1. Go to 'Menu section or Order section'
2. Click on 'Reload'
3. See error

**Expected behavior**
It should redirect to that section only !!

**Comment by kashika13** [comment]
please assign this to me . I want to work on it.

**Comment by c4coderandcreator** [comment]
Assigned to you @kashika13  !! Go for it !!
