### ISSUE TITLE
Track Order : close button  is not visible

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#152]
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/70572678/11dd05d9-7fed-4089-87da-cd002453437b)
Design / Fix it for both normal mode and dark mode !!

**Comment by ThanushaMandala** [comment]
@c4coderandcreator would like to work on this issue, can it be assigned to me?

**Comment by c4coderandcreator** [comment]
Go for it @ThanushaMandala

**Comment by c4coderandcreator** [comment]
Hey @ThanushaMandala  the design is already implemented try redirecting order status back button to order section !!

**Comment by shoaib-31** [comment]
@ThanushaMandala Are you still working on this?

**Comment by c4coderandcreator** [comment]
This is fixed !!

**Comment by ThanushaMandala** [comment]
sure thanks for letting me know @c4coderandcreator
