### ISSUE TITLE
scroll fix in About us section !!

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#153]
when we click on "About us" it scrolls bit down and got attached to navbar.
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/70572678/7f08e3c8-c8d1-4bbb-89bd-5b140467b685)

It should look like this on click and user will not have a scroll margin on right 
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/70572678/f471e777-255e-48b2-9b23-256c97b56840)

**Comment by sansarmaske** [comment]
Hi, I would like to give it a shot!

**Comment by love-sonkar** [comment]
Hey Brother i'm working on it

**Comment by sansarmaske** [comment]
Alright! No worries.

**Comment by Varad0014** [comment]
Hey, @love-sonkar I have a fix for this. It works but I am not sure if its the correct way to fix this problem. Can I suggest?

**Comment by c4coderandcreator** [comment]
> Hey, @love-sonkar I have a fix for this. It works but I am not sure if its the correct way to fix this problem. Can I suggest?

Suggestions are always welcome !!

**Comment by c4coderandcreator** [comment]
> Hey Brother i'm working on it

Assigned to you !!

**Comment by love-sonkar** [comment]
@Varad0014  yes bro please tell me

**Comment by c4coderandcreator** [comment]
> Alright! No worries.

Hey @sansarmaske  !! Thank you for your interest in Flavour Fusion, I suggest you to review the website and try finding the issues/bugs !! Create a new issue !!

**Comment by Varad0014** [comment]
I changed the href attribute of About anchor tag from #allaboutus to just # and it worked as expected.

**Comment by sansarmaske** [comment]
Sure! Will do that.

**Comment by love-sonkar** [comment]
great job buddy it works thanks for suggestion ,
Btw you can Create PR for this it's your's now

**Comment by Varad0014** [comment]
@love-sonkar I have contributed a lot. You can go ahead with the PR.

**Comment by Varad0014** [comment]
I don't think we will be able to fix this by making changes to css as the the position sticky of header is creating problems when anchor tag directs to the allaboutus section

**Comment by love-sonkar** [comment]
yes brother I've been trying to fix it for the last hour thanks for suggesting now it's fixed
