### ISSUE TITLE
Order History : Search should show some cafe result

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#16]
When user starts typing for the cafe by name , it will show search by cafe name , when pressing search it will return a dummy value (list of cafe).

**Comment by JTateCC** [comment]
Interesting Project and I'd like to contribute. Could you assign this to me.

**Comment by c4coderandcreator** [comment]
Sure @JTateCC  !!  Work on it

**Comment by c4coderandcreator** [comment]
Hey @JTateCC  There are lot more PR's approved to the repo, please pull the repo first to your local machine before you start working on this , (To avoid conflicts ) !!

**Comment by VIDYA1980** [comment]
i have added this feature ,check my pr

**Comment by c4coderandcreator** [comment]
Hey @VIDYA1980 thanks for your effort
