### ISSUE TITLE
Fix: Missing forgot password link in sign in page

### ISSUE THREAD

**Issue by Varad0014** [c4coderandcreator/Flavour-Fusion#160]
**Describe the bug**
There is no forgot password link in sign in page.

**To Reproduce**
1. Go to sign in page

**Expected behavior**
There should be a forgot password link also

**Screenshots**
<img width="933" alt="sign-in" src="https://github.com/c4coderandcreator/Flavour-Fusion/assets/77493105/171c3f51-5cdd-4db1-b39e-354b01a7526c">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]
 - Version [latest]

**Additional context**
Someone can add a forgot password link

**Comment by Srishdwi02** [comment]
I can fix this. Please assign me this issue. Also, I feel that the UI can be enhanced by adding border radius to the elements.

**Comment by c4coderandcreator** [comment]
Hey @Srishdwi02  assigned to you !! Make sure you follow the contributing guidelines !!
