### ISSUE TITLE
order status : back button

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#167]
It should redirect to order section not home !!

**Comment by jude-san** [comment]
@c4coderandcreator Please details on what to be done.

**Comment by c4coderandcreator** [comment]
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/70572678/cf9e67de-a02c-4de0-a3a2-ee7d4876f16d)
The highlighted button should redirect to order section , currently it redirects to home

**Comment by jude-san** [comment]
assign the task to me please

**Comment by c4coderandcreator** [comment]
Hey @jude-san  this is fixed !!

**Comment by jude-san** [comment]
> Hey @jude-san this is fixed !!

@c4coderandcreator noted
