### ISSUE TITLE
Your cart section does not work properly

### ISSUE THREAD

**Issue by divyansh14kr** [c4coderandcreator/Flavour-Fusion#168]
**Describe the bug**
While ordering and selecting from the given list, your cart section remains empty.

**To Reproduce**
1. Go to orders section via the navbar
2. select any items to order
3. the my cart section remains empty and only the total amount of the order is shown

**Expected behavior**
the my cart section should contain the items ordered, their quantity and the total price

**Screenshots**
<img width="1440" alt="Screenshot 2023-10-21 at 8 17 31 AM" src="https://github.com/c4coderandcreator/Flavour-Fusion/assets/118956824/db6e9f0e-4dcf-4593-96b0-962a50e23ed4">

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all

**Comment by c4coderandcreator** [comment]
Hey @divyansh14kr  go for it !!

**Comment by aarjun8060** [comment]
Hi @c4coderandcreator I also want to work on this issue. would you assign me ?
