### ISSUE TITLE
Menu Items should be linked to order now section !!

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#173]
- all menu items can be picked from add to cart while adding items to to cart !! RN it is having dummy data !!

**Comment by vishnukaushik** [comment]
@c4coderandcreator Could you assign this to me? I can work on it.
Could you please elaborate little bit more on the issue?
Thanks!

**Comment by c4coderandcreator** [comment]
These are menu Items 
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/70572678/92f2ffd6-eb1f-4fa7-83eb-c81580108ea1)

This should also be included in this section 
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/70572678/008999a6-0e35-4b75-a283-6a160e79f847)

**Comment by vishnukaushik** [comment]
Got it. Could you assign this issue to me?

**Comment by c4coderandcreator** [comment]
Hey @vishnukaushik  it is assigned to you !!

**Comment by vishnukaushik** [comment]
@c4coderandcreator I see that the menu items are all hard-coded. Should we hard-code all items in the "add to card" section?

**Comment by c4coderandcreator** [comment]
open the menu in small screen you will find the menu items in a list , i like to add the same functionality within the order now section with pricing included !! no matter what logic you apply just implement it

**Comment by vishnukaushik** [comment]
@c4coderandcreator Created #177. Please review when you get a chance.
Thanks!

**Comment by c4coderandcreator** [comment]
> @c4coderandcreator Created #177. Please review when you get a chance. Thanks!

create the PR with UI-Improvement branch

**Comment by vishnukaushik** [comment]
@c4coderandcreator created #179 with UI-Improvement branch
