### ISSUE TITLE
Like counter for Menu Items !! 

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#175]
Menu Items can get likes 
Max Like allowed 2 per user

**Comment by Arceen** [comment]
I can do this. Can you please assign this to me?

**Comment by c4coderandcreator** [comment]
Sure @Arceen  go for it !! Make sure you follow the contributing guidelines !!

**Comment by Arceen** [comment]
Hey @c4coderandcreator  Loved working on the project! Please check the PR, if its working like you want. Thanks!

**Comment by c4coderandcreator** [comment]
> Hey @c4coderandcreator Loved working on the project! Please check the PR, if its working like you want. Thanks!

sure @Arceen  please create thee PR with UI-Improvement branch

**Comment by Arceen** [comment]
I've merged it with the UI-Improvement branch. Check PR. Thanks!
