### ISSUE TITLE
Include Dummy User Feedbacks !! 

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#176]
Include "Our Reviews" in Footer section . The theme should match with website !!

**Comment by Petsamuel** [comment]
I would like to work on this 

Kindly give more detail about this issue

**Comment by c4coderandcreator** [comment]
- create dummy reviews for the website
- link it in section "Our Reviews"
- Our Reviews will be placed in footer section
- //The reviews are dummy reviews just for demonstration

**Comment by Petsamuel** [comment]
@c4coderandcreator 

![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/65086865/7c25c7fc-86ec-49f1-8c84-df611ba79705)

**Comment by c4coderandcreator** [comment]
Ya great !!  3-4 more and in slide way !!

**Comment by c4coderandcreator** [comment]
Hey @Petsamuel  Any Update

**Comment by Petsamuel** [comment]
im just seeing this I'll work on this now, sorry about that.

**Comment by c4coderandcreator** [comment]
> im just seeing this I'll work on this now, sorry about that.

ok !

**Comment by Petsamuel** [comment]
> > im just seeing this I'll work on this now, sorry about that.
> 
> ok !

Hi @c4coderandcreator, sorry for reaching out to you late 
I run into complications with my PC.
I may not deliver this issue on time... 

In case there is anyone who wants to work you can assign it to them.

**Comment by c4coderandcreator** [comment]
Sure @Petsamuel  !! Thanks for informing !! Also I wish you resolve your issues soon !!
