### ISSUE TITLE
minor UI update on order-landing page

### ISSUE THREAD

**Issue by goobric** [c4coderandcreator/Flavour-Fusion#18]
Hi @Shybymh 
the hover state of the buttons on the Order Now, Order History, and Track Order cards, changes to white, visually this is not distinctive for those with visual impairments.
I would like to update the hover state, to give a darker salmon/orange color to assist those with visual impairments.
https://c4coderandcreator.github.io/Flavour-Fusion/#order-landing

Can I be assigned to this please
![231016_gh_flavorFusion_issue](https://github.com/c4coderandcreator/Flavour-Fusion/assets/23141638/0dc8c719-d424-4765-a7a3-a79adac81bc5)

**Comment by c4coderandcreator** [comment]
Hi @goobric  !! I just came to create that issue and found that you already had it, great though !! Give it a Go !!

**Comment by c4coderandcreator** [comment]
There are lot more PR's approved to the repo, please pull the repo first to your local machine before you start working on this , (To avoid conflicts ) !!
