### ISSUE TITLE
Fix: Dark mode theme issue after reloading

### ISSUE THREAD

**Issue by Srishdwi02** [c4coderandcreator/Flavour-Fusion#182]
**Describe the bug**
When the website is in dark mode and we reload the website, the theme changes to light mode again.

**To Reproduce**
1. Change to dark mode using the sun button on navbar.
2. Refresh the website.

**Expected behavior**
The website should remain in the dark mode after reloading.

**Screenshots**

https://github.com/c4coderandcreator/Flavour-Fusion/assets/138107242/01388f01-d439-4372-ac51-4fc6ac826903

**Desktop (please complete the following information):**
 - OS: [all]
 - Browser[all]
 - Version [latest]

**Comment by Srishdwi02** [comment]
I can fix this. Please assign this to me.

**Comment by c4coderandcreator** [comment]
Thank you @Srishdwi02  !! For your efforts !! I appreciate it !! Also I would like you to document your contribution and drop it at coderandcreator@gmail.com !! I need it for my documentation !!
