### ISSUE TITLE
Minor UI change on the home page

### ISSUE THREAD

**Issue by uddiptojana10** [c4coderandcreator/Flavour-Fusion#19]
![FlavorFusion](https://github.com/c4coderandcreator/Flavour-Fusion/assets/117717963/ffd7eefe-5a32-4fb4-9402-5e2df4e9d9b4)
instead of this, a better toggle button can be used to switch between dark mode and light mode.
Willing to work on this if assigned.

**Comment by uddiptojana10** [comment]
yes its okay.

**Comment by c4coderandcreator** [comment]
Additionally for your info : while creating PR create it with Dark-mode branch !!

**Comment by c4coderandcreator** [comment]
You just made a valuable contribution @uddiptojana10
