### ISSUE TITLE
bug: swiper slider component disortion 🙅🏻❌ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [c4coderandcreator/Flavour-Fusion#190]
**Describe the bug**
- The bug is about the disortion of swiper sliders, border radius of each sliders are being causing disortion during sliding.

**To Reproduce**
1. Go to 'Menu' section of Flavor Fusion
2. See the error during sliding

**Expected behavior**
- Border radius needs to be applied to the Swiper component's wrapper instead of applying them on individual sliders

**Screenshots**
![Capture_2023-10-22-19-13-03](https://github.com/c4coderandcreator/Flavour-Fusion/assets/92252895/4e872b4f-8ed5-4eff-839a-8b9f90149180)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Firefox
 - Version: 104.2

**Smartphone (please complete the following information):**
 - Device: Nokia 6.1
 - OS: Android 10
 - Browser: Chrome
 - Version: 113

**Comment by 0xabdulkhalid** [comment]
Hey there @c4coderandcreator 👋🏻,

Please make sure to assign this issue to me as soon as possible to make the work done quickly.

Thank you!

**Comment by c4coderandcreator** [comment]
@0xabdulkhalid  Assigned
