### ISSUE TITLE
Order History : search button color and border is not good . 

### ISSUE THREAD

**Issue by VirendrKumarYadav** [c4coderandcreator/Flavour-Fusion#197]
I want to change this.

**Comment by c4coderandcreator** [comment]
go for it and create the PR with UI improvement branch

**Comment by VirendrKumarYadav** [comment]
i Have created branch name -updateClrAndBorder..like that
i hope that's fine

**Comment by c4coderandcreator** [comment]
Thanks for your time and effort but please try to improve it and match the buttons with theme !!
