### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#2]
UI needs to be redesigned in few sections like : Menu and Order

**Comment by SunilKumar-K** [comment]
can you share any designs are available for that.

**Comment by c4coderandcreator** [comment]
Hi @SunilKumar-K The live website is there, You can review it and Try modifying that design as best as you can, keeping user experience in mind !!

**Comment by Shybymh** [comment]
I can work on the Order section redesigning.

**Comment by c4coderandcreator** [comment]
Assigned to you @Shybymh  !!

**Comment by c4coderandcreator** [comment]
Hey @Shybymh 

There are lot more PR's approved to the repo, please pull the repo first to your local machine before you start working on this , (To avoid conflicts ) !!

**Comment by c4coderandcreator** [comment]
No Worries Will help you out !! Your hard work will not fade away In front of me !! 😄🫂 !! Good Work @Shybymh

**Comment by c4coderandcreator** [comment]
This is resolved by @Shybymh

**Comment by c4coderandcreator** [comment]
@Shybymh your section is breaking after the merge !! plz fix it

**Comment by Shybymh** [comment]
On it!

**Comment by c4coderandcreator** [comment]
Ya I request you to create PR with UI-Improvement branch !! once you are done

**Comment by Shybymh** [comment]
Should I close the current pull request?

**Comment by c4coderandcreator** [comment]
I will close it !! make sure your fetch the main branch , and while creating PR create it with UI-Improvement branch

**Comment by Shybymh** [comment]
Will do!

**Comment by c4coderandcreator** [comment]
Hey @Shybymh  any update on this issue ?

**Comment by Shybymh** [comment]
Just started working on it. Saw a lot of commits happened overnight, I've updated my repo with main, all 96 of them. I will check for conflicts and do PR to the UI branch.

**Comment by c4coderandcreator** [comment]
Great to hear that !! Take your time !! @Shybymh  !! There is no rush !!

**Comment by Shybymh** [comment]
I have a question.Below is the screen shot of the Order section in the site now.
![screencapture-c4coderandcreator-github-io-Flavour-Fusion-2023-10-17-11_34_00](https://github.com/c4coderandcreator/Flavour-Fusion/assets/97486205/9651d1c9-741f-4dc6-ae72-f4b3b383ab03)

 And my version is below.
![screencapture-127-0-0-1-5500-Flavour-Fusion-index-html-2023-10-17-11_34_28](https://github.com/c4coderandcreator/Flavour-Fusion/assets/97486205/6bc2f300-3af9-48b8-92dc-24cd81b422c6)
Which one do you prefer in your site?

**Comment by Shybymh** [comment]
I made the "Your Cart' in case some one (or me) wants to work on displaying the items in the cart later.

**Comment by c4coderandcreator** [comment]
Your design is soothing, I would like you to try adding a feature in it "whatever is added to cart the items will show up on the white space of the Right card and total will remain in its position as it is now" 

I hope you understand my concern !!

**Comment by Shybymh** [comment]
Can we do it after finishing this PR?

**Comment by c4coderandcreator** [comment]
> Can we do it after finishing this PR?

Ya @Shybymh  !! I agree to this !!

**Comment by c4coderandcreator** [comment]
> I have followed all the steps (other than naming the branch different from repo's ) fetched from main, cleared conflicts, pushed and raised PR. Hopefully nothing will break. Although I've found Dark Mode is not friendly in Order page. The background-color of "Menu' and "Your Cart" stays white but the text in them go white making them invisible.

These two issues which you have pointed is being taken care !!

**Comment by Shybymh** [comment]
> > Can we do it after finishing this PR?
> 
> Ya @Shybymh !! I agree to this !!

@c4coderandcreator You want a card with "Items in the cart"?

**Comment by c4coderandcreator** [comment]
> > > Can we do it after finishing this PR?
> > 
> > 
> > Ya @Shybymh !! I agree to this !!
> 
> @c4coderandcreator You want a card with "Items in the cart"?

No no !! 

This layout in picture I addressed it as card in words !!

**Comment by Shybymh** [comment]
@c4coderandcreator I have questions. Please check Discord.

**Comment by c4coderandcreator** [comment]
> @c4coderandcreator I have questions. Please check Discord.

Sure !!
