### ISSUE TITLE
Minor UI Improvements 

### ISSUE THREAD

**Issue by GD0910** [c4coderandcreator/Flavour-Fusion#20]
While Switching to dark theme , the order now button is not readable 

![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/88530462/38c7f28c-94a7-4a5e-ae9a-046c49e5b065)

I would like to make this changes under Hacktoberfest 2023

**Comment by GD0910** [comment]
hi @c4coderandcreator i would like to work this issue and a suggestion to change the dark theme toogle button as well

**Comment by c4coderandcreator** [comment]
Sure !! Go for it , but while creating PR create it with Dark-Mode branch !!

**Comment by c4coderandcreator** [comment]
There are lot more PR's approved to the repo, please pull the repo first to your local machine before you start working on this , (To avoid conflicts ) !!

**Comment by GD0910** [comment]
> There are lot more PR's approved to the repo, please pull the repo first to your local machine before you start working on this , (To avoid conflicts ) !!

 I know but I have found another error that dark mode doesn’t work in tracking screen only the. Text color changes to white in dark mode so I’m working on that 
I saw that someone was working on solving this color issue and maybe I can work on tracking page

**Comment by ranixhirani** [comment]
Hello, I would like to work on the header of the website to make it look more appealing by including the logo and doing some designing in the nav bar.

**Comment by c4coderandcreator** [comment]
hey @ranixhirani  a separate issue as per your request has been assigned to you !! Please work on that !!

**Comment by c4coderandcreator** [comment]
@ranixhirani  check the issue #51  in the issue section !!

**Comment by c4coderandcreator** [comment]
> Hello, I would like to work on the header of the website to make it look more appealing by including the logo and doing some designing in the nav bar.

Please create a new issue so that I can easily assign it to you !!
