### ISSUE TITLE
Responsiveness issue of header.

### ISSUE THREAD

**Issue by aviraljain19** [c4coderandcreator/Flavour-Fusion#207]
**Is your feature request related to a problem? Please describe.**
There is some problem in responsiveness of header.

**Describe the solution you'd like**
I would like to fix this issue. @c4coderandcreator  can you assign this issue to me?

**Additional context**
![Screenshot 2023-10-24 045116](https://github.com/c4coderandcreator/Flavour-Fusion/assets/100090730/beb0ca88-ed38-4925-95d7-84105f28c8e4)

**Comment by Lok-ii** [comment]
I have worked on the header before, I fixed it earlier but now there's one more button (reservations) which probably is causing the issue. 

@c4coderandcreator can you assign it to me?
