### ISSUE TITLE
Fix dark mode issues

### ISSUE THREAD

**Issue by AndreCancella** [c4coderandcreator/Flavour-Fusion#21]
Hello, how are you? Analyzing the website I noticed some problems when activating the dark mode in colors and letters and I would like to fix these problems.
Very bright button making it difficult to understand the word on it and other things.
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/57547457/888bbf09-ea7c-4048-9eae-7ee5ab32e8a1)

**Comment by c4coderandcreator** [comment]
Hi @AndreCancella  !! Sure Go for it , just keep in mind while creating PR , create it with Dark-Mode Branch not the main branch !! so that I will test it out better !!
