### ISSUE TITLE
Footer UI improvements

### ISSUE THREAD

**Issue by Anshkaran7** [c4coderandcreator/Flavour-Fusion#22]
![Screenshot 2023-10-16 182329](https://github.com/c4coderandcreator/Flavour-Fusion/assets/106963118/d2824efd-15f0-4a90-a41b-a4894d016cdc)

I want to fix UI in the footer section

**Comment by c4coderandcreator** [comment]
Sure Give it a go !!

**Comment by teeshaa** [comment]
@c4coderandcreator i would like to work on this please assign me.
