### ISSUE TITLE
Some more UI changes on the home page

### ISSUE THREAD

**Issue by uddiptojana10** [c4coderandcreator/Flavour-Fusion#23]
![FlavorFusion (1)](https://github.com/c4coderandcreator/Flavour-Fusion/assets/117717963/99060d45-7e3a-4b24-a972-bf142e6a4039)
the logo font looks almost identical to the navbar links making it a bit confusing. The logo font could be made bigger/bolder. 
Willing to work on this if assigned

**Comment by c4coderandcreator** [comment]
You want to increase the Font Size ?
