### ISSUE TITLE
UI Improvement 

### ISSUE THREAD

**Issue by Ayush80555** [c4coderandcreator/Flavour-Fusion#24]
I can add Tilt JS library, So that when user hovers over the image then it interacts with mouse movement
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/116146717/0bd5f094-c9da-445d-964e-c09cc59e1dd2)

On cards too 
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/116146717/16eba650-fd76-410a-b63c-0e2dac3197af)

and Some minor hover effects on texts like in navbar 
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/116146717/4fd1119a-8f2c-4efd-a6cf-91992244d7bd)

assign me this one

**Comment by c4coderandcreator** [comment]
Ok Give it a go !! Make sure you create PR with UI-Improvements branch.

**Comment by Ayush80555** [comment]
@c4coderandcreator I've made a PR, kindly review and merge it.

**Comment by Ayush80555** [comment]
Thanks, will contribute more
