### ISSUE TITLE
Reservation popup doesn't have close button

### ISSUE THREAD

**Issue by ShrujanaReddy** [c4coderandcreator/Flavour-Fusion#242]
Reservation popup doesn't have close button

1. Go to 'https://c4coderandcreator.github.io/Flavour-Fusion/'
2. Click on 'Reservation'
3. See error

**Expected behavior**
A close button is expected.

<img width="955" alt="image" src="https://github.com/c4coderandcreator/Flavour-Fusion/assets/130744023/58605969-31e0-4109-bf44-a05128e3b344">

**Comment by ShrujanaReddy** [comment]
I would like to work on this. Do assign this issue to me.

**Comment by c4coderandcreator** [comment]
Assigned to you @ShrujanaReddy

**Comment by c4coderandcreator** [comment]
also make sure to follow the contributing guidelines and your code doesn't break on small screen !!
