### ISSUE TITLE
Improved Hovering feature 🐞

### ISSUE THREAD

**Issue by SaiSantosh2209** [c4coderandcreator/Flavour-Fusion#25]
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/83724995/0f71713f-2c0b-4791-a88c-5b9c0272d10f)

**Comment by c4coderandcreator** [comment]
Please elaborate the issue you want to fix !!

**Comment by SaiSantosh2209** [comment]
i can enhance the hovering effect by changing the color and the size of the box while hovering it

**Comment by c4coderandcreator** [comment]
Thank you @SaiSantosh2209   !! For your valuable contribution !! Leave a Star to the Repo For Us !!
