### ISSUE TITLE
Equalizing margins under "Orders" and "Our Reviews" titles

### ISSUE THREAD

**Issue by Shybymh** [c4coderandcreator/Flavour-Fusion#265]
In the landing page, the margins under "Orders" and "Our Reviews" titles are different. It will look better with same gap between the titles and content. Please assign it to me.
<img width="1344" alt="Screenshot 2023-11-05 at 11 07 50 PM" src="https://github.com/c4coderandcreator/Flavour-Fusion/assets/97486205/2f423fd4-b1ce-4047-a84c-661a09d14b02">

**Comment by c4coderandcreator** [comment]
Assigned !! Please verify the responsive thing !!

**Comment by c4coderandcreator** [comment]
Thank you @Shybymh
