### ISSUE TITLE
Improve Overall Styling and UI Enhancements

### ISSUE THREAD

**Issue by TonyStark-19** [c4coderandcreator/Flavour-Fusion#272]
Hi, team!

I’ve been exploring this project and found it to be a great initiative. I would love to contribute by improving the overall styling to enhance the user experience. As I have found some areas which need improvements.

Areas which caught my eye are:

Navbar, hover effects, footer , Sign in and reservation page

All these have some issues which will be fixed by me.

Additionally, I’m open to collaborating on other improvements based on feedback and suggestions from the team.

Let me know your thoughts, and I’d be happy to start working on it!

**Comment by c4coderandcreator** [comment]
assigned to you @TonyStark-19
