### ISSUE TITLE
Homepage needs Animation

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#3]
Homepage is quite static : One can add animations to images on Homepage

**Comment by ChiragAgg5k** [comment]
I can work on this. assign it to me

**Comment by c4coderandcreator** [comment]
Hi @ChiragAgg5k  !! It is assigned to you !!

**Comment by c4coderandcreator** [comment]
Hi @ChiragAgg5k  There are lot more PR's approved to the repo, please pull the repo first to your local machine before you start working on this , (To avoid conflicts ) !!

**Comment by ChiragAgg5k** [comment]
Okay 👍

**Comment by c4coderandcreator** [comment]
Hey @ChiragAgg5k  any update on this ?

**Comment by ChiragAgg5k** [comment]
working on it

**Comment by c4coderandcreator** [comment]
ok @ChiragAgg5k Take your time 🫂

**Comment by c4coderandcreator** [comment]
you can play with that plate like rotating for few seconds and then it stays static for a few seconds and vice versa !!
