### ISSUE TITLE
bright/dark theme  button improvement

### ISSUE THREAD

**Issue by akshad36** [c4coderandcreator/Flavour-Fusion#30]

**Comment by akshad36** [comment]
the button of dark /light theme design can be improved

**Comment by c4coderandcreator** [comment]
Hi @akshad36 

While making the PR Keep below points in mind :
- create PR with Dark-Mode
- Attach the ss/demo of the updated design
- Describe your changes

**Comment by c4coderandcreator** [comment]
This is already completed !!
