### ISSUE TITLE
Dynamically generating the year.

### ISSUE THREAD

**Issue by lunoos** [c4coderandcreator/Flavour-Fusion#33]
I was going through the code and found that the year in 'All rights are reserved'  is hard coded,
<p class="footer__copy">&#169; **2023** FlavorFusion. All right reserved</p>
I want to make it dynamic.

Can you please assign it to me with hackoctoberfest tag.

Thanks.

**Comment by c4coderandcreator** [comment]
Hi @lunoos go for it !! Once done , Make sure you create the PR with UI-Improvement branch !!

**Comment by c4coderandcreator** [comment]
Hi @lunoos  !! This is already done !! Please look into some other issue/improvements !!

**Comment by lunoos** [comment]
Okay
