### ISSUE TITLE
enhancement in Nav, fonts , and optimizations delivery

### ISSUE THREAD

**Issue by aditya4567uk** [c4coderandcreator/Flavour-Fusion#36]
enhancement in Nav section UI and footer , 
Integration with some good looking fonts 
Optimization of files and assets for load times less bandwidth requirement.

Could you pls assign me me this task? I can contribute in your awesome website

**Comment by c4coderandcreator** [comment]
Hi @aditya4567uk  I really like the way you pointed out things !! And Ya You can work on it !!

Please keep in mind :
-  Pull the code before creating the PR
-  Create PR with UI-Improvement branch not the main branch
-  SS/ Demo of changes are heartily welcomed in PR

**Comment by aditya4567uk** [comment]
sure thing!

**Comment by c4coderandcreator** [comment]
@aditya4567uk  Any Update ?

**Comment by vedantheda** [comment]
Could you assign this to me? I'll surely get it done by tomorrow

**Comment by c4coderandcreator** [comment]
I appreciate your effort !! Assigned !!

**Comment by c4coderandcreator** [comment]
Hey @vedantheda  any update ?

**Comment by vedantheda** [comment]
working on it!

**Comment by vedantheda** [comment]
Hi, I had a suggestion, that we should make the navbar green, because it looks quite weird in dark mode. If we make it green, it'll look cohesive with the website and it'll be uniform. Let me know if you want it like that

**Comment by c4coderandcreator** [comment]
Hey @vedantheda  I feel a ss of your suggestions will give us a better visualization !!

**Comment by vedantheda** [comment]
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/90914768/cbdd5748-3c55-4a80-9dac-018e497ab80b)

**Comment by c4coderandcreator** [comment]
Approved @vedantheda  go for it !

**Comment by vedantheda** [comment]
how do I make a PR that answers this issue?

**Comment by c4coderandcreator** [comment]
Just create it with UI-Improvement branch , this repo has 2 branch check it !!

**Comment by vedantheda** [comment]
ok I have made one, can you check it and assign the hacktoberfest label?
