### ISSUE TITLE
Update title and favicon

### ISSUE THREAD

**Issue by unm07** [c4coderandcreator/Flavour-Fusion#4]
Update the title and favicon to make the website look more professional
![Screenshot 2023-10-16 084745](https://github.com/c4coderandcreator/Flavour-Fusion/assets/110920768/4c60a2bd-f1a0-4e93-b3ab-944d99fd01ed)

**Comment by unm07** [comment]
May I work on this?

**Comment by c4coderandcreator** [comment]
Sure @unm07  !! Go Ahead and Fix it !!
