### ISSUE TITLE
Fixing the 'Sign In' card overflow

### ISSUE THREAD

**Issue by avg77** [c4coderandcreator/Flavour-Fusion#46]
Hey there, @c4coderandcreator!
I'd like to fix the 'Sign In' card overflow for better alignment and look.

Attached screenshots shows the changes to be implemented:

1)                                      Before:-
![bf1](https://github.com/c4coderandcreator/Flavour-Fusion/assets/91598955/0a9b5791-ff22-4a36-a705-887d392fd713)

2)                                      After:-
![af1](https://github.com/c4coderandcreator/Flavour-Fusion/assets/91598955/f1693ac4-6603-4d12-a9a5-600b69ab8b6c)

Kindly assign me this issue under appropriate tags.
Thank You!

**Comment by c4coderandcreator** [comment]
Good Find @avg77  !! Assigned to you !!

**Comment by c4coderandcreator** [comment]
Please keep in mind :
-  Pull the code before creating the PR (just to safeguard your efforts)
-  Create PR with UI-Improvement branch not the main branch
-  SS/ Demo of changes are heartily welcomed in PR
