### ISSUE TITLE
Fix : Sign in page close button

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#57]
close button on sign in page is not responsive , it should have a fixed position and it should be responsive.

**Comment by awsmdeep** [comment]
Hey @c4coderandcreator i hope you're doing good , can you please assign me this issue?

**Comment by c4coderandcreator** [comment]
Hey @awsmdeep  !! Sure you can work on it !! Just keep in mind while creating PR , create it with UI-Improvement branch not the main branch

**Comment by c4coderandcreator** [comment]
This is resolved now !
