### ISSUE TITLE
Fix : About us section

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#58]
About us section is hiding in navbar

**Comment by Lok-ii** [comment]
I can look into it, can you please assign it to me?

**Comment by c4coderandcreator** [comment]
Sure @Lok-ii  !! Go ahead !!  create PR with UI-Improvement branch not the main branch

**Comment by Lok-ii** [comment]
@c4coderandcreator Fixed it and also created a PR with the UI-Improvement branch.

**Comment by c4coderandcreator** [comment]
Thank you @Lok-ii   !! For your valuable contribution !! Leave a Star to the Repo For Us !!
