### ISSUE TITLE
Tilt Js required in About us section for each image 

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#59]
Like we have tilt js applied on homepage we should apply it on about us page !!

**Comment by buneeIsSlo** [comment]
@c4coderandcreator I'd love to give this a shot!

**Comment by c4coderandcreator** [comment]
ok !! Go for it !! Good luck

**Comment by buneeIsSlo** [comment]
@c4coderandcreator I do have a small doubt. Do I add the tilt to the whole card, or just the image?

**Comment by c4coderandcreator** [comment]
@buneeIsSlo  !! Just the image !!

**Comment by buneeIsSlo** [comment]
@c4coderandcreator Got it. I'll make the PR in a bit.
