### ISSUE TITLE
Add to cart functionality should be synced with Each menu items

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#61]
User should add, delete, review items of cart in menu section !!

**Comment by Ajiboso-Adeola** [comment]
I would like to work on this issue

**Comment by c4coderandcreator** [comment]
Sure @Ajiboso-Adeola  !! Make Sure you read the contributing guidelines before starting !!

**Comment by c4coderandcreator** [comment]
Hey @Ajiboso-Adeola  Any Update ?
