### ISSUE TITLE
Alignment Issue with Sign Up/Sign In Page Close Button

### ISSUE THREAD

**Issue by LakshanRukantha** [c4coderandcreator/Flavour-Fusion#64]
I've noticed a minor alignment problem on the sign-up and sign-in pages. The close button does not appear to be properly aligned. This could affect the overall user experience.

Screenshot: 
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/64830641/b16679b3-24c7-4534-8f05-9fd6ef0268da)

**Comment by LakshanRukantha** [comment]
I'd like to take on the task of addressing this alignment issue. Please assign it to me, and I'll work on resolving it.

**Comment by c4coderandcreator** [comment]
It is already fixed !! Thanks @LakshanRukantha 
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/70572678/29ba181d-0631-4ec5-97be-b53e5b9a32fe)

**Comment by LakshanRukantha** [comment]
I think it is not still responsive.


https://github.com/c4coderandcreator/Flavour-Fusion/assets/64830641/8c2b7b93-d6d6-4fa3-9ebe-856b4acbb472

**Comment by c4coderandcreator** [comment]
Hey @LakshanRukantha  actually it is a bug, if the browser visibility is set to 100% the cross is at exact position i.e Top-Right. But if it is reduced to 80% or less it acts weird !! Good find , I will say !! Please fix it , also make it responsive and try to create PR with 
UI-Improvement branch not with the main branch !!

**Comment by LakshanRukantha** [comment]
@c4coderandcreator Got it. I'll take care of fixing it.
