### ISSUE TITLE
Fix :  UI not responsive 

### ISSUE THREAD

**Issue by GD0910** [c4coderandcreator/Flavour-Fusion#67]
Navbar is not responsive 
try to make navbar responsive 
ss : 
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/88530462/a12e4aee-4aec-497a-9393-70d9eab175fe)

**Comment by c4coderandcreator** [comment]
Good Find @GD0910  !! Are you able to fix it ?

**Comment by GD0910** [comment]
No i'm working on another bug fix

**Comment by GD0910** [comment]
Better if you assign this to person who's interested

**Comment by c4coderandcreator** [comment]
ok Thanks for helping @GD0910  🫂 Even I count your efforts as contribution ❤️

**Comment by GD0910** [comment]
> ok Thanks for helping @GD0910 🫂 Even I count your efforts as contribution ❤️
🙌

**Comment by c4coderandcreator** [comment]
Hey @Lok-ii Loki this issue contain a bug which is breaking the nav items !! No need of design here , you can refer the live website !!

**Comment by Lok-ii** [comment]
Okay, thanks @c4coderandcreator! I will fix it, can you please assign it to me?

**Comment by c4coderandcreator** [comment]
Sure Go for it @Lok-ii

**Comment by c4coderandcreator** [comment]
read the contributing guideline https://github.com/c4coderandcreator/Flavour-Fusion/blob/main/CONTRIBUTING.md and follow it. Also you can continue it here  only no need to create duplicate issue

**Comment by GD0910** [comment]
> I am not sure if I should create a new issue or just mention it here itself but....
> 
> There is one more issue which is related to navbar responsiveness, basically the name is flowing out of the navbar on smaller screens, I will fix it as well.
> 
> ![Screenshot 2023-10-17 192908](https://user-images.githubusercontent.com/129180844/275859383-97311549-b5cd-4d1b-9093-c35112725081.png)
> 
> Also, the menu icon is not visible in the dark mode. And when the icon is clicked the navbar list hides the menu icon and we can't click on it, the menu icon hides behind the navbar list. To click on the icon, we have to scroll so that the sticky navbar sticks to the top and then the menu icon is visible.
> 
> ![Screenshot 2023-10-17 193519](https://user-images.githubusercontent.com/129180844/275861656-e3589841-d1d9-4213-8d33-e4272aae188f.png)

you dont need to create another issue 
just update this issue in the same  PR
I raised this issue as i saw that it wasnt responsive for smaller devices

**Comment by c4coderandcreator** [comment]
No worries Take your time @Lok-ii
