### ISSUE TITLE
Fix order now section 

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#82]
in dark mode the contents gets hidden

**Comment by adnanxali** [comment]
Can I try this one ?

**Comment by Tulsi5990** [comment]
Hey , I want to work on this issue. Can u please assign me?

**Comment by c4coderandcreator** [comment]
Go for it !! Make sure you follow contributing guidelines !!

**Comment by Ajiboso-Adeola** [comment]
I'd love to work on this issue

**Comment by c4coderandcreator** [comment]
Sure @Ajiboso-Adeola you can give it a try but at the time of creating PR pull the Repo to check if these things are already completed or not !!

**Comment by Varad0014** [comment]
Hey @c4coderandcreator, are you talking about the tracking order section? If yes, then can I fix it?

**Comment by c4coderandcreator** [comment]
Hey @Varad0014 Assigned !!
