### ISSUE TITLE
fix close button in order now and track order

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#83]
the close buttons on top of both the sections  are messed up

**Comment by dakshsinghrathore** [comment]
hey @c4coderandcreator I would like to work on this issue, kindly assign it to me !

**Comment by c4coderandcreator** [comment]
Sure go for it, make sure to read the contributing guidelines !!

**Comment by c4coderandcreator** [comment]
hey @dakshsinghrathore  Any Update ?

**Comment by vedantheda** [comment]
Hi, could you assign this to me so I can work on this problem?
