### ISSUE TITLE
Responsiveness Issue in Nav Items on small screen

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#84]
Nav items are breaking on phone size

**Comment by Ferdinand-Ogama** [comment]
Hello, I am ready to work on this issue. Could you assign me?

**Comment by c4coderandcreator** [comment]
Ya Sure, Always pull the code before creating a PR !! Parallel approvals are there !!

**Comment by c4coderandcreator** [comment]
@sagarxjadhav  follow the contributing guidelines !!

**Comment by c4coderandcreator** [comment]
@sagarxjadhav  @Ferdinand-Ogama  This is already completed !! Please look for other issues or create a new one if you find any !!

**Comment by Ferdinand-Ogama** [comment]
Okay.
