### ISSUE TITLE
Fix : Order now appearance on Desktop

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#97]
**Fix : Order Now **
Order now section is way to large reduce it height and width

**To Reproduce**
1. Go to 'Homepage'
2. Click on 'orders'
3. Scroll down to 'order now'

**Expected UI**
It should have free space around the corners it is taking too much space.

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: All

**Additional context**
If you are contributing , read the contributing guidelines first.

**Comment by Atheke** [comment]
I would like to work on this issue and also some assistance in understanding and contributing

**Comment by c4coderandcreator** [comment]
Sure @Atheke Assigned to you !! Don't Forget to give a follow to my Github for more upcoming open source projects and Leave a Star to the Repo For Us !!

**Comment by Atheke** [comment]
I am sorry but can you please elaborate on the issue so that i can have a better understanding as the order now card in the bottom of the landing page is well aligned with the other cards

**Comment by c4coderandcreator** [comment]
Its size should be decreased by 25% and it should me made responsive !!
