### ISSUE TITLE
Fix : close button in order now section

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#98]
**close button fix**
button is bit weird 

**Expected appearance**
A clear and concise button is need to close that section.

**Screenshots**
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/70572678/4f424a00-8b23-4043-9d80-ddd1862419d4)

**Comment by Ferdinand-Ogama** [comment]
@c4coderandcreator Can I work on this?

**Comment by c4coderandcreator** [comment]
Sure @Ferdinand-Ogama  Assigned to you !!

**Comment by Ferdinand-Ogama** [comment]
Please don't reassign it to someone else. Thanks :)

**Comment by c4coderandcreator** [comment]
@Ferdinand-Ogama  Noted !! Make sure to follow the contributing guidelines and create PR with UI-Improvement branch not the main branch

**Comment by Ferdinand-Ogama** [comment]
Noted.

**Comment by Ferdinand-Ogama** [comment]
@c4coderandcreator Sorry for asking, but Just to save time. Kindly tell me which action you perform on the website to see the button.

**Comment by Ferdinand-Ogama** [comment]
What I can see is the close button

**Comment by tharanithar-r** [comment]
Hello. I am interested in working on this issue. Kindly assign it to me.

**Comment by c4coderandcreator** [comment]
@tharanithar-r follow the contributing guidelines !!
