### ISSUE TITLE
Fix : Responsiveness Issue of Order Now section

### ISSUE THREAD

**Issue by c4coderandcreator** [c4coderandcreator/Flavour-Fusion#99]
**Order Now section is not responsive**
It breaks of smaller screen

**To Reproduce**
1. Go to 'homepage'
2. Click on 'orders'
3. Scroll  to 'order now'
4. Reduce the screen size in inspect mode
5. See error

**Expected behavior**
It should be highly responsive

**Screenshots**
![image](https://github.com/c4coderandcreator/Flavour-Fusion/assets/70572678/e1c0b46e-30ad-4ba4-a533-7c15a5a9af8c)

**Smartphone (please complete the following information):**
 - Device: All
 - OS: Any
 - Browser: All

**Comment by coderSuren** [comment]
@c4coderandcreator I would like to work on this issue, please assign it to me

**Comment by c4coderandcreator** [comment]
@coderSuren  Assigned to you !!
